accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView,LoginView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = 'account'


urlpatterns = [
    path('signup/',views.SignUpPage.as_view(),name='signup'),
    path('login/',LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='reset/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='reset/password_reset_complete.html'), name='password_reset_complete'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset/password_reset_confirm.html'), name='password_reset_confirm'),
]

userdata/urls.py
from django.urls import path
from . import views

app_name = 'user_data'


urlpatterns = [
    path('post_upload/',views.BasicUploadView.as_view(),name='data'),
    path('post_data/',views.DisplayImages.as_view(),name='pic'),
    path('detail/<int:pk>',views.UserDataDet.as_view(template_name='details.html'),name='getid'),
    path('edit/<int:pk>',views.UserDetailUpdate.as_view(template_name='userdetailedit.html'),name='edit'),
    path('delete/<int:pk>',views.UserDetailDelete.as_view(template_name='userdelete.html'),name='delete'),

]

vivekweb/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('allauth.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('user/',include('userdata.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User,PermissionsMixin
# Create your models here.

class SignPage(User,PermissionsMixin):

    def __str__(self):
        return '@{}'.format(self.username)

userdata/models.py
from django.db import models
from django.contrib.auth.models import User


class UserDataDetail(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=128,blank=False)
    description = models.TextField(max_length=400, blank=True, null=True)
    image = models.FileField(upload_to= 'photos')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class MultipleImg(models.Model):
    name = models.ForeignKey(UserDataDetail,on_delete=models.CASCADE)
    picture = models.FileField(upload_to= 'photos',blank=True,null=True)


    def __str__(self):
        return self.name.user

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UserForm(UserCreationForm):

    class Meta:
        fields = ('first_name','last_name','username','email','password1','password2')

        model = get_user_model()

        def __init__(self,*args,**kwargs):

            super().__init__(*args,**kwargs)
            self.fields['username'].label = 'Display Name'
            self.fields['email'].label = 'Email'

userdata/forms.py
from django import forms
from .models import UserDataDetail,MultipleImg



class PostFormDetail(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Folder Title'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Enter somthing here'}))
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple':True}))
    class Meta:
        model = UserDataDetail
        fields = ('title','description','image',)

accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView
from django.urls import reverse_lazy
from .forms import UserForm
# Create your views here.


class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contact.html'

class SignUpPage(CreateView):
	form_class = UserForm
	template_name = 'registration/signup.html'
	success_url = reverse_lazy('login')

userdata/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import PostFormDetail
from django.views import View as djviews
from .models import UserDataDetail,MultipleImg
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

@method_decorator(login_required, name='dispatch')
class DisplayImages(ListView):

    def get(self, request):
        User_list = UserDataDetail.objects.filter(user=request.user)

        return render(self.request, 'pic.html', {'data':User_list })


class UserDataDet(CreateView):
    model = UserDataDetail
    fields = ['user','title', 'description','image']

    def get(self, request,pk):
        detail = UserDataDetail.objects.get(id=pk)
        return render(request,'details.html',{'detail':detail})


@method_decorator(login_required, name='dispatch')
class BasicUploadView(djviews):
    def get(self, request):
        User_Data =PostFormDetail()
        return render(self.request, 'data.html', {'data':User_Data })

    def post(self, request,):
        form = PostFormDetail(self.request.POST,self.request.FILES)
        pic = request.FILES.getlist('image')
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            for i in pic:
                pictures = MultipleImg(name = form, picture= i)
                pictures.save()

            return redirect('home')


class UserDetailUpdate(UpdateView): 
    model = UserDataDetail
    success_url = reverse_lazy('home') 
    fields = ['title', 'description','image']


class UserDetailDelete(DeleteView): 
    model = UserDataDetail
    success_url = reverse_lazy('home')

vivekweb/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'home.html'

accounts/templates/about.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% bootstrap_messages %}
{% block title %}

About
{% endblock %}


{% block body %}
<div class="container">
	<h1>Cloud Service</h1>
	<h1>..........</h1>
	<h1>........</h1>
</div>
    
{% endblock %}

accounts/templates/contact.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% bootstrap_messages %}
{% block title %}

Contact
{% endblock %}


{% block body %}
<div class="container">
	<h1>Contact Number</h1>
	<h1>Vivek Singh Adhikari</h1>
	<h1>9968038609<h1>
	<h1>........</h1>
</div>
    
{% endblock %}

accounts/templates/reset/password_reset_complete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Reset Complete
{% endblock%}

{% block body %}
<div class="main" style="background-image: url({% static 'images/bg-pic.jpg' %})">
	<div class="container" style="color: white; font-size: 18px; margin-top: 20px">
		<p>
	    	Your password has been set. You may go ahead and <a href="{% url 'account:login' %}" style="color: red">Log In</a> now.
	  	</p>
	</div>
</div>
{% endblock%}

accounts/templates/reset/password_reset_confirm.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Reset Confirm
{% endblock%}

{% block body %}
<div class="main" style="background-image: url({% static 'images/bg-pic.jpg' %})">
  {% if validlink %}
    <h1>Change password</h1>

    <form  method="post">
      {% csrf_token %}
      <div class="container" style="color: white; font-size: 18px; margin-top: 20px">
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Change password</button>
      </div>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
</div>
{% endblock%}

accounts/templates/reset/password_reset_done.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Reset Done
{% endblock%}

{% block body %}
<div class="main" style="background-image: url({% static 'images/bg-pic.jpg' %})">
	<div class="container" style="color: white; font-size: 18px; margin-top: 20px">
		<p>
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p>
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <div style="text-align: center">
		  <h7 style="font-size:15px">Back to </h7><a href="{% url 'home' %}" style="color: red">Home</a><h7 style="font-size:12px">..</h7>
		</div>
	</div>
</div>
{% endblock%}

accounts/templates/reset/password_reset_form.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Password Reset forum
{% endblock%}

{% block body %}
<div class="main" style="background-image: url({% static 'images/bg-pic.jpg' %})">
	<h1 style="color: white; font-size: 30px; margin-top: 50px">Forgot password</h1>

	<form  method="post">
		{% csrf_token %}
		<div class="container" style="color: white; font-size: 18px; margin-top: 50px">
			{{ form|crispy }}
		<button type="submit" class="btn btn-primary">Submit</button>
		</div>
	</form>
</div>
{% endblock%}

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
{% load socialaccount %}

<html lang="en">
<head>
    <meta charset="UTF-8">
       <link rel="stylesheet" type="text/css" href="{% static 'css/formsty.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <title>{% block title %} {% endblock%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>
<body>
    <div>
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <div class="container">
                <a href="{% url 'home' %}" class="navbar-brand">
                    <img src="{% static 'images/logo.png' %}" height="28" alt="CloudService">
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav">
                        <a href="{% url 'home' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'account:about' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'account:contact' %}" class="nav-item nav-link">Contact</a>
                        <!-- <a href="#" class="nav-item nav-link disabled" tabindex="-1">Reports</a> -->
                    </div>
                    <div class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <a href="{% url 'user_data:data' %}" class="nav-item nav-link">Upload</a>
                            <a href="{% url 'user_data:pic' %}" class="nav-item nav-link">My Data</a>
                            <p class="navbar-brand" style="color: black;font-size: 18px">Welcome: {{user}}</p>
                            <a href="{% url 'account:logout' %}" class="nav-item nav-link">Logout</a>
                        {% else %}
                            <a href="{% url 'account:login' %}" class="nav-item nav-link">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </div>

        {% block body %}

        {% endblock %}
    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
CLOUD HOME
{% endblock%}

{% block body %}
<div class="main" style="background-image: url({% static 'images/bg-pic.jpg' %})">
    <div class="container">
        <div class="main_body">
            <h1>Let go into the cloud</h1>
            <p>This website stores your personal data in our cloud database. You can add images,songs,video etc.</p>
        </div>
    </div>
        <div class="atag">
            {% if user.is_authenticated %}
                <a href="{% url 'user_data:data' %}" class="button">Upload</a>
            {% else %}
                <a href="{% url 'account:login' %}" class="button">Login</a>
            {% endif %}
        </div>
</div>

{% endblock%}

userdata/templates/data.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
DATA
{% endblock%}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
   
    <div class="container" style="color: black; font-size: 18px; margin-top: 20px">
        {{ data|crispy }}
        <button type="submit" class="btn btn-primary">Upload</button>
    </div>

</form>
{% endblock%}

userdata/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
PICTURE
{% endblock%}

{% block body %}

<div class="container" style="margin-top: 25px;">
	<div style="text-align: center;" >
		<a href="{% url 'user_data:pic' %}" style="padding-left: 30px;">Back</a>
		<a href="{% url 'user_data:edit' detail.id %}" >Edit</a>
		<a  href="{% url 'user_data:delete' detail.id %}" >Delete</a>
	</div>
	<h1 style="color:red;text-align:center;font-size: 40px">{{detail.title}}</h1>
	<h1 style="color:black;text-align:center;font-size: 25px">{{detail.description}}</h1> 
	<div class="card-group">
		<div class="row">
			{% for i in detail.multipleimg_set.all %}
				<div class="card col-md-4"  style="margin-bottom: 5px;">
					<img class="card-img-top" src= "{{ i.picture.url }}" alt="Avatar" >
				</div>
			{% endfor %}
		</div>
			
	</div>
</div>

    
        
        

{% endblock%}

userdata/templates/pic.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
PICTURE
{% endblock%}

{% block body %}
<div class="container" style="margin-top: 25px">
	<h1 style="color:green;text-align:center;font-size: 30px">Welcome {{user.first_name}}</h1> 
	<div class="card-group">
		<div class="row">
			{% for i in data %}
				<div class="card col-md-4"  style="margin-bottom: 5px;">
					<a href="{% url 'user_data:getid' i.id %} ">
						<img class="card-img-top" src= "{{ i.image.url }}" alt="Avatar" >
					</a>
					<div class="card-body">
						<a href="{% url 'user_data:getid' i.id %} ">
							<h3 class="card-title">{{ i.title }}</h3>
						</a>
						<p class="card-text">{{ i.description }}</p>

					</div>
				</div>
				
			{% endfor %}
		</div>
	</div>
</div>
        
        

{% endblock%}

userdata/templates/userdelete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Delete
{% endblock%}

{% block body %}
<div class="main" style="background-image: url({% static 'images/bg-pic.jpg' %})">
	<h1 style="color: #fff;margin-top: 30px;font-size: 30px">Detail Delete?</h1>

	<form  method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="container" style="color: #fff; font-size: 18px; margin-top: 20px">
			{{ form|crispy }}
			Are you sure you want to delete this contact?
			<button type="submit" class="btn btn-primary">Submit</button>
		</div>
	</form>
</div>
{% endblock%}

userdata/templates/userdetailedit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Edit
{% endblock%}

{% block body %}
<div class="main" style="background-image: url({% static 'images/bg-pic.jpg' %})">
	<h1 style="color: #fff;margin-top: 5px;font-size: 18px">Detail Update</h1>
	<form  method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="container" style="color: white; font-size: 18px; margin-top: 20px">
			{{ form|crispy }}
			<button type="submit" class="btn btn-primary">Submit</button>
		</div>
	</form>
</div>
{% endblock%}